# Generated by Django 5.0.3 on 2024-05-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_myuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_agent',
        ),
    ]
