# Generated by Django 5.0.3 on 2024-05-14 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_myuser_is_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='agents/logos/')),
                ('telephone', models.CharField(max_length=20)),
                ('intro', models.TextField()),
                ('address_line1', models.CharField(max_length=120)),
                ('address_line2', models.CharField(blank=True, max_length=120)),
                ('town', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('location_lat', models.CharField(max_length=100)),
                ('location_lon', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
