version: "3"
services:
  backend:
    build: .
    container_name: brightmove-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  frontend:
    build: ./frontend
    container_name: brightmove-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
