# Generated by Django 5.0.3 on 2024-07-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='feature_img',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
