# Generated by Django 5.0.3 on 2024-03-18 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('added_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('address_line1', models.CharField(max_length=120)),
                ('address_line2', models.CharField(blank=True, max_length=120)),
                ('town', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('postcode', models.CharField(max_length=10)),
                ('property_type', models.CharField(choices=[('Detached', 'Detached'), ('Semi-detached', 'Semi-detached'), ('Flat', 'Flat'), ('Bangalow', 'Bangalow')], max_length=20)),
                ('bedroom', models.IntegerField()),
                ('toilet', models.IntegerField()),
                ('price_type', models.CharField(choices=[('Offers over', 'Offers over'), ('Fixed price', 'Fixed price')], default='Offers over', max_length=20)),
                ('price', models.BigIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_property', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('is_feature', models.BooleanField(default=False)),
                ('alt_text', models.CharField(max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property')),
            ],
        ),
    ]
