# Generated by Django 5.0.3 on 2024-05-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertywishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location_lat',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='location_lon',
            field=models.CharField(default=20, max_length=20),
            preserve_default=False,
        ),
    ]
