# Generated by Django 5.0.3 on 2024-05-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_location_lat_property_location_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='location_lat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='location_lon',
            field=models.CharField(max_length=100),
        ),
    ]
