# Generated by Django 4.2.1 on 2023-06-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_propertywishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSearchTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('search_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
