# Generated by Django 5.0.3 on 2024-05-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_myuser_is_agent_agent'),
        ('property', '0004_alter_property_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_property', to='account.agent'),
        ),
    ]
