# Generated by Django 5.0.3 on 2024-05-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='owner',
            new_name='agent',
        ),
    ]
